github.com:
    users:
        NopeImNotHere:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: NopeImNotHere
